### ISSUE TITLE
Update colors on dashboard

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#168]
Kibana dashboard we need a way to color visualisation gadgets like this correctly

**Comment by MaNe2020** [comment]
@GINAGC I think we can close this one as per comment here:
https://www.elastic.co/guide/en/kibana/current/lens.html, we are not going to be able to change color
![image (6)](https://user-images.githubusercontent.com/70108899/115884139-de5d6880-a44e-11eb-9ec4-83abb62215c8.png)

**Comment by MaNe2020** [comment]
@GINAGC @kekesimarti can you assign this to someone who can also give it a try because I cannot see how we can implement this in some simple manner.

Adding here few references that can help maybe:
https://www.oreilly.com/library/view/mastering-kibana-6x/9781788831031/1dfad91c-75db-4c20-9985-a2b3be89d62c.xhtml#:~:text=To%20do%20this%2C%20we%20can,change%20the%20colors%20of%20visualizations

https://discuss.elastic.co/t/changing-palette-and-default-color-in-kibana/114140/2


And also the link from above, shared previously.

**Comment by GINAGC** [comment]
@dpatel7 can you give it a try?

**Comment by dpatel7** [comment]
@GINAGC I will try this once i am done with end-to-end test

**Comment by kekesimarti** [comment]
We don't need this anymore
