### ISSUE TITLE
Make a variation of the "clear-data-and-status-folder' 

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#231]
We need a variation of the "clear-data-and-status-folder' which is something like 'mark-all-hd2-files-unprocessed' which basically:
* moves back all files in the 'processed' folder back into the 'data' folder
* resets the metadata
* deletes the other json files (events, report)
This should be faster than copying the files again

**Comment by ggrig** [comment]
Dinis Cruz (GW CTO and CISO)
btw, just noticed that we need a variation of the "clear-data-and-status-folder' which is something like 'mark-all-hd2-files-unprocessed' which basically moves back all files in the 'processed' folder back into the 'data' folder resets the metadata
deletes the other JSON files (events, report) this should be faster than copying the files again (which is what I have been doing, since that requires an actual file copy and the calculation of a file hash)

**Comment by ggrig** [comment]
This duplicates https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/228

**Comment by kekesimarti** [comment]
Thanks @ggrig I'm closing this one.
