### ISSUE TITLE
Snyk SCA - Medium issues relating to requirements.txt

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#608]
![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/40557186-9636-4d3d-b010-1db45db8dae3)

**Comment by rajmbcoderx** [comment]
@chrisdiao / @GINAGC There seems to be no fix for this issue and I am not sure why SNYK is complaining about this issue.

The libraries websocket-client and certifi are required by jupyter and we have no control over it. The only problem that is reported are the certificate that are being uses i.e. LGPL-2.1 and MPL2.0, these are some of the standard licences and are used by lot of open source projects.

We can modify SNYK configuration to ignore LGPL-2.1 and MPL2.0 licenses. Currently there are no vulnerabilities for the library mentioned above, all the vulnerabilities have been fixed in the versions that we are using
https://snyk.io/vuln/pip:websocket-client
https://snyk.io/vuln/pip:certifi

**Comment by chrisdiao** [comment]
Hello @rajmbcoderx , we can close this task, @PEpetra also agree to have this ignore as of the moment.

![image](https://user-images.githubusercontent.com/68153062/127153259-6e74d810-1e69-4db2-af9f-acfef9a95530.png)
